config/routes.rb
Pdtms::Application.routes.draw do

  

  resources :polls

  resources :fotos

  resources :photos

  resources :galleries

  resources :previdenciasocials

  resources :direitoshumanos

  resources :soberania

  resources :educacaos

  resources :trabalhismos

  resources :diretoriomunicipals

  resources :diretorioestaduals

  resources :executivas

  resources :lideres

  resources :historia

  resources :events

  resources :moves

  resources :articles

  resources :newsses

  resources :newsfs

  resources :news_secondaries

  resources :news_featureds

  root :to => 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  ActiveAdmin.routes(self)

  resources :news_categories

  get "home/index"

  get 'home/noticiassecundarias'

  get 'flags/labour'

  get 'flags/education'
  
  get 'flags/sovereignty'

  get 'flags/humanrights'

  get 'flags/foresight' 

  get 'movements/black'

  get 'movements/woman'

  get 'movements/social'

  get 'movements/union'

  get 'movements/retired' 

  get 'powers/executive'

  get 'powers/legislative'

  get 'agenda/events'

  get 'contact/where'

  get 'pdt/executive'

  get 'pdt/history'

  get 'pdt/leaders'

  get 'pdt/municipal'

  get 'pdt/state'

  get 'home/newsfall'

  get 'home/newssall'

  get 'home/shownoticesec'

  get 'home/shownoticedef'

  get 'home/readarticle'

  match "contact", to: "contact#where", as: "contact"
  match "dispatch_email", to: "contact#dispatch_email", as: "dispatch_email", method: :post
  match "vota", to: "home#vota_enquete", as: "vota"
 

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/article.rb
class Article < ActiveRecord::Base
  mount_uploader :imagearticle, ImageNewsUploader
  attr_accessible :author, :content, :date, :description, :imagearticle, :title
end

app/models/educacao.rb
class Educacao < ActiveRecord::Base
  attr_accessible :content
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :city, :date, :description, :title
end

app/models/executiva.rb
class Executiva < ActiveRecord::Base
  attr_accessible :content
end

app/models/foto.rb
class Foto < ActiveRecord::Base
  belongs_to :gallery
  attr_accessible :imagefoto, :gallery_id
  mount_uploader :imagefoto, ImageNewsUploader
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  
  attr_accessible :description, :name

  has_many :fotos

  validates_presence_of :name
  
  validates_uniqueness_of :name
end

app/models/historium.rb
class Historium < ActiveRecord::Base
  attr_accessible :content, :image
end

app/models/lidere.rb
class Lidere < ActiveRecord::Base
  attr_accessible :content, :name
end

app/models/move.rb
class Move < ActiveRecord::Base
  attr_accessible :link
end

app/models/newsf.rb
class Newsf < ActiveRecord::Base

  mount_uploader :imagenews, ImageNewsUploader

  attr_accessible :author, :content, :date, :description, :title, :imagenews

  
end

app/models/newss.rb
class Newss < ActiveRecord::Base
  mount_uploader :imagenews, ImageNewsUploader
  attr_accessible :author, :content, :date, :description, :title, :imagenews
  
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :fouranswer, :oneanswer, :questionmain, :threeanswer, :twoanswer
end

app/models/poll_vote.rb
class PollVote < ActiveRecord::Base
  belongs_to :poll
  attr_accessible :vote, :poll_id
end

app/models/soberanium.rb
class Soberanium < ActiveRecord::Base
  attr_accessible :content
end

app/models/trabalhismo.rb
class Trabalhismo < ActiveRecord::Base
  attr_accessible :content
end

app/controllers/newsfs_controller.rb
class NewsfsController < InheritedResources::Base
end

app/helpers/flags_helper.rb
module FlagsHelper
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/newsfs_helper.rb
module NewsfsHelper
end

app/helpers/pdt_helper.rb
module PdtHelper
end

app/views/newsfs/_form.html.erb
<%= form_for @newsf, :html => { :multipart => true } do |f| %>
  <% if @newsf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newsf.errors.count, "error") %> prohibited this newsf from being saved:</h2>

      <ul>
      <% @newsf.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :imagenews %><br />
    <%= f.file_field :imagenews %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/newsfs/edit.html.erb
<h1>Editing newsf</h1>

<%= render 'form' %>

<%= link_to 'Show', @newsf %> |
<%= link_to 'Back', newsfs_path %>

app/views/newsfs/index.html.erb
<h1>Listing newsfs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Content</th>
    <th>Author</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @newsfs.each do |newsf| %>
  <tr>
    <td><%= newsf.title %></td>
    <td><%= newsf.description %></td>
    <td><%= newsf.content %></td>
    <td><%= newsf.author %></td>
    <td><%= newsf.date %></td>
    <td><%= image_tag newsf.imagenews_url(:thumb) %></td>
    <td><%= link_to 'Show', newsf %></td>
    <td><%= link_to 'Edit', edit_newsf_path(newsf) %></td>
    <td><%= link_to 'Destroy', newsf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Newsf', new_newsf_path %>

app/views/newsfs/new.html.erb
<h1>New newsf</h1>

<%= render 'form' %>

<%= link_to 'Back', newsfs_path %>

app/views/newsfs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @newsf.title %>
</p>

<p>
  <b>Description:</b>
  <%= @newsf.description %>
</p>

<p>
  <b>Content:</b>
  <%= @newsf.content %>
</p>

<p>
  <b>Author:</b>
  <%= @newsf.author %>
</p>

<p>
  <b>Date:</b>
  <%= @newsf.date %>
</p>
<p>
  <b>Image:</b>
  <%= image_tag @newsf.imagenews_url(:thumb) %>
</p>


<%= link_to 'Edit', edit_newsf_path(@newsf) %> |
<%= link_to 'Back', newsfs_path %>