config/routes.rb
Pdtms::Application.routes.draw do

  

  resources :polls

  resources :fotos

  resources :photos

  resources :galleries

  resources :previdenciasocials

  resources :direitoshumanos

  resources :soberania

  resources :educacaos

  resources :trabalhismos

  resources :diretoriomunicipals

  resources :diretorioestaduals

  resources :executivas

  resources :lideres

  resources :historia

  resources :events

  resources :moves

  resources :articles

  resources :newsses

  resources :newsfs

  resources :news_secondaries

  resources :news_featureds

  root :to => 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  ActiveAdmin.routes(self)

  resources :news_categories

  get "home/index"

  get 'home/noticiassecundarias'

  get 'flags/labour'

  get 'flags/education'
  
  get 'flags/sovereignty'

  get 'flags/humanrights'

  get 'flags/foresight' 

  get 'movements/black'

  get 'movements/woman'

  get 'movements/social'

  get 'movements/union'

  get 'movements/retired' 

  get 'powers/executive'

  get 'powers/legislative'

  get 'agenda/events'

  get 'contact/where'

  get 'pdt/executive'

  get 'pdt/history'

  get 'pdt/leaders'

  get 'pdt/municipal'

  get 'pdt/state'

  get 'home/newsfall'

  get 'home/newssall'

  get 'home/shownoticesec'

  get 'home/shownoticedef'

  get 'home/readarticle'

  match "contact", to: "contact#where", as: "contact"
  match "dispatch_email", to: "contact#dispatch_email", as: "dispatch_email", method: :post
  match "vota", to: "home#vota_enquete", as: "vota"
 

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/article.rb
class Article < ActiveRecord::Base
  mount_uploader :imagearticle, ImageNewsUploader
  attr_accessible :author, :content, :date, :description, :imagearticle, :title
end

app/models/educacao.rb
class Educacao < ActiveRecord::Base
  attr_accessible :content
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :city, :date, :description, :title
end

app/models/executiva.rb
class Executiva < ActiveRecord::Base
  attr_accessible :content
end

app/models/foto.rb
class Foto < ActiveRecord::Base
  belongs_to :gallery
  attr_accessible :imagefoto, :gallery_id
  mount_uploader :imagefoto, ImageNewsUploader
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  
  attr_accessible :description, :name

  has_many :fotos

  validates_presence_of :name
  
  validates_uniqueness_of :name
end

app/models/historium.rb
class Historium < ActiveRecord::Base
  attr_accessible :content, :image
end

app/models/lidere.rb
class Lidere < ActiveRecord::Base
  attr_accessible :content, :name
end

app/models/move.rb
class Move < ActiveRecord::Base
  attr_accessible :link
end

app/models/newsf.rb
class Newsf < ActiveRecord::Base

  mount_uploader :imagenews, ImageNewsUploader

  attr_accessible :author, :content, :date, :description, :title, :imagenews

  
end

app/models/newss.rb
class Newss < ActiveRecord::Base
  mount_uploader :imagenews, ImageNewsUploader
  attr_accessible :author, :content, :date, :description, :title, :imagenews
  
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :fouranswer, :oneanswer, :questionmain, :threeanswer, :twoanswer
end

app/models/poll_vote.rb
class PollVote < ActiveRecord::Base
  belongs_to :poll
  attr_accessible :vote, :poll_id
end

app/models/soberanium.rb
class Soberanium < ActiveRecord::Base
  attr_accessible :content
end

app/models/trabalhismo.rb
class Trabalhismo < ActiveRecord::Base
  attr_accessible :content
end

app/controllers/fotos_controller.rb
class FotosController < InheritedResources::Base
end

app/helpers/flags_helper.rb
module FlagsHelper
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/pdt_helper.rb
module PdtHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/fotos/_form.html.erb
<%= form_for(@foto) do |f| %>
  <% if @foto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foto.errors.count, "error") %> prohibited this foto from being saved:</h2>

      <ul>
      <% @foto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :imagefoto %><br />
    <%= f.file_field :imagefoto %>
  </div>
  <div class="field">
    <%= f.label :gallery %><br />
    <%= f.text_field :gallery %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fotos/edit.html.erb
<h1>Editing foto</h1>

<%= render 'form' %>

<%= link_to 'Show', @foto %> |
<%= link_to 'Back', fotos_path %>

app/views/fotos/index.html.erb
<h1>Listing fotos</h1>

<table>
  <tr>
    <th>Imagefoto</th>
    <th>Gallery</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fotos.each do |foto| %>
  <tr>
    <td><%= foto.imagefoto %></td>
    <td><%= foto.gallery %></td>
    <td><%= link_to 'Show', foto %></td>
    <td><%= link_to 'Edit', edit_foto_path(foto) %></td>
    <td><%= link_to 'Destroy', foto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Foto', new_foto_path %>

app/views/fotos/new.html.erb
<h1>New foto</h1>

<%= render 'form' %>

<%= link_to 'Back', fotos_path %>

app/views/fotos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Imagefoto:</b>
  <%= @foto.imagefoto %>
</p>

<p>
  <b>Gallery:</b>
  <%= @foto.gallery %>
</p>


<%= link_to 'Edit', edit_foto_path(@foto) %> |
<%= link_to 'Back', fotos_path %>